//
//  SearchInteractor.swift
//  MusicApp
//
//  Created by Поляндий on 23.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func makeRequest(request: Search.Model.Request.RequestType)

}

protocol SearchDataStore {
    var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic {

    var networkService = NetworkService()
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    //var name: String = ""

    // MARK: Do something (and send response to SearchPresenter)

    func makeRequest(request: Search.Model.Request.RequestType) {
        if worker == nil {
            worker = SearchWorker()
        }
        switch request {
        case .some:
            print("interactor .some")
        case .getTracks(let searchTerm):
            print("interactor .getTracks")
            networkService.fetchTracks(searchText: searchTerm) { [weak self] (searchResponse) in
                self?.presenter?.presentData(response: Search.Model.Response.ResponseType.presentTracks(searchResponse: searchResponse))
            }
        }
    }
}

//extension SearchInteractor: SearchDataStore {
//
//}
